model_list:
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ${OPENAI_API_KEY}
      api_base: https://api.openai.com/v1
  - model_name: groq/gpt-oss-20b
    litellm_params:
      model: openai/gpt-oss-20b
      api_key: ${GROQ_API_KEY}
      api_base: https://api.groq.com/openai/v1
  - model_name: lamma.cpp
    litellm_params:
      model: openai/qwen3-4b-instruct
      api_base: http://0.0.0.0:8080/v1
      api_key: dummy-token
      custom_llm_provider: openai

litellm_settings: # module level litellm settings - https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py
  drop_params: True